version: "3.8"

services:
  django_app:
    image: piratehammad/notes-app:latest
    container_name: "django_cont"
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
